apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-requested
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mem-requested
  template:
    metadata:
      labels:
        app: mem-requested
    spec:
      containers:
      - name: mem-requested
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "1", "-t", "600s"]
        resources:
          requests:
            memory: "5Gi"
            cpu: ".5"
---
apiVersion: v1
kind: Service
metadata:
  name: mem-requested-service
spec:
  ports:
  - port: 8080
  selector:
    app: mem-requested