apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-requested
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  cpu-requested
  template:
    metadata:
      labels:
        app: cpu-requested
    spec:
      containers:
      - name: cpu-requested
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "1", "-t", "600s"]
        resources:
          requests:
            memory: "50M"
            cpu: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-requested-service
spec:
  ports:
  - port: 8080
  selector:
    app: cpu-requested