kind: Deployment
apiVersion: apps/v1
metadata:
  name: liveness-probe-fail
  namespace: default
  labels:
    app: liveness-probe-fail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-probe-fail
  template:
    metadata:
      labels:
        app: liveness-probe-fail
    spec:
      containers:
      - name: liveness-probe-fail
        image: nginx
        ports:
        - containerPort: 80
        command: ["/bin/bash"]
        args: ["sed", "-i", "'s/listen.*/listen 81;/'", "/etc/nginx/conf.d/default.conf", "&&", "/etc/init.d/nginx", "reload"]
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 81
          initialDelaySeconds: 30
          periodSeconds: 20