kind: Deployment
apiVersion: apps/v1
metadata:
  name: liveness-probe-success
  namespace: default
  labels:
    app: liveness-probe-success
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-probe-success
  template:
    metadata:
      labels:
        app: liveness-probe-success
    spec:
      containers:
      - name: liveness-probe-success
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20