apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-limited
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mem-limited
  template:
    metadata:
      labels:
        app: mem-limited
    spec:
      containers:
      - name: mem-limited
        image: polinux/stress
        ports:
        - containerPort: 8080
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "600", "--backoff", "15000000"]
        resources:
          requests:
            memory: "50M"
            cpu: "100m"
          limits:
            memory: "100M"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mem-limited-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31000
  selector:
    app: mem-limited